version: '3.8'

services:
  client:
    container_name: frontend
    restart: always
    build: ./client
    ports:
      - "4000:3000"
    depends_on:
      - server
  server:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app
  database:
    container_name: db
    restart: always
    build: ./db
    ports:
      - "5432:5432"
